# Uncomment the next line to define a global platform for your project
#platform :ios, '11.0'

target 'Clase1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clase1
	pod 'Alamofire', '~> 4.5.1'
	pod 'AlamofireImage', '~> 3.3'

end
